[env:uno_r4_wifi]
build_flags = -DINCLUDE_uxTaskGetStackHighWaterMark=1
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200

lib_deps =
    # Use exact names/IDs so PIO can't miss them
    arduino-libraries/Servo @ ^1.2.1
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    arduino-libraries/Stepper @ ^1.1.3